project: 
  type: website

## Below was test to convert to book, also pdf document class below (not functional yet)
# book:
#   title: "Test-Book"
#   author: "Marylou Staman"
#   date: "12/9/2024"
#   chapters:
#     - index.qmd
#     - intro.qmd
#     - summary.qmd
#     - references.qmd
# 
# bibliography: references.bib

website: 
  page-navigation: true
  title: "PSD Small Boats" 
  site-url: "https://pifsc-protected-species-division.github.io/PSD-SmallBoats/" 
  repo-url: "https://github.com/PIFSC-Protected-Species-Division/PSD-SmallBoats"
  repo-actions: [edit, source, issue]
  favicon: content/images/favicon.ico
# https://iconifier.net/
  
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-1.0"
  
  sidebar:
    background: "#D9E3E4"
    logo: "Boatcontent/images/Psd_logo_NB.png"
    favicon: images/favicon.ico
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://sites.google.com/a/noaa.gov/noaa-small-boat-program/home
        text: "NOAA Small Boat Program"
        target: _blank
        #"target: _blank" makes link pop out to new window
      - icon: github
        href: https://github.com/PIFSC-Protected-Species-Division/PSD-SmallBoats
        text: "Github Repository"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      - section: Boatcontent/Requirements.qmd
        text: Requirements
        contents: 
          - href: Boatcontent/Documents.qmd
            text: Documents
          - href: Boatcontent/Training.qmd
            text: Training
          - href: Boatcontent/Equipment.qmd
            text: Equipment
      - section: Boatcontent/Boats.qmd
        text: Boats
        contents: 
          - href: Boatcontent/BoatRecords.qmd
            text: Records

format:
  html:
    theme:
      light: [cosmo, theme.scss] 
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true
  # pdf:
  #   documentclass: scrreprt


filters:
  - include-files.lua
  - quarto

  
