---
title: "Equipment Manuals"
format: html
---
[Inventory of Equipment Manuals](https://docs.google.com/spreadsheets/d/1FXicB0RQnHugSoNtR7bG4VoQNtiiXxcNLOKWgiC-4eU/edit?usp=drive_link){.external target="_blank"}

## Refrigerators
-   [Unique UGP 6F Chest Freezer](https://drive.google.com/file/d/1DDZwK3tHJcCs7tsN5q28xiVZjZlVC6Wu/view?usp=sharing){.external target="_blank"}
-   [Unique UGP 3 Propane Refrigerator](https://drive.google.com/file/d/1y6pULlaaBeCWplmFi8UqsTw-qdg21s5T/view?usp=sharing){.external target="_blank"}
-   [SunDazer Solar Freezer](https://drive.google.com/file/d/1UE-5wG-UyGAmPiB94_8paX2mphDRdW7u/view?usp=sharing){.external target="_blank"}
-   [Steca PF166 and PF240 Solar Freezer](https://drive.google.com/file/d/1iU0dcmge6u6rDLN9wc9iZKiBGqjCMitY/view?usp=sharing){.external target="_blank"}

## Generators, Hoist, Etc
-   [Generator Protocol](https://docs.google.com/document/d/1GYtTmnWQ9ThCNy880yv8ZuFGJgudDykZ/edit?usp=sharing&ouid=111160936144270501572&rtpof=true&sd=true){.external target="_blank"}
-   [Generator EU1000](https://drive.google.com/file/d/1KOdDUfczSagOzY9VSxZFqeN5G7iQQeC6/view?usp=sharing){.external target="_blank"}
-   [Generator EB10000](https://drive.google.com/file/d/1x_qnOHvA1U3INpI9c9wC2nMNhX3YMLGG/view?usp=sharing){.external target="_blank"}
-   [Generator EB6500X](https://drive.google.com/file/d/1dDjx7o89o4bJEWTJJIgEiBEaZlI95V68/view?usp=sharing){.external target="_blank"}
-   [Dayton Manual Chain Hoist](https://drive.google.com/file/d/1fhWlhv0eL6UaVKXNwBvb7jzW8asFbKrZ/view?usp=sharing){.external target="_blank"}

## Freezer and Battleborn Battery Solar System
-   [Solar Freezer Set Up and Use](https://docs.google.com/document/d/1f14ZM1hRWA6GIH65vKVVS9IFApp1lWG1hRDWZrWP5o0/edit?usp=sharing){.external target="_blank"}
-   [Solar Controllers for Battleborn Batteries](https://drive.google.com/file/d/19SFvva9SHtpodHz1LggR4sWRDc4hCas9/view?usp=sharing){.external target="_blank"}
-   [PF166-H and PF240-H Refrigerator / Freezer](https://drive.google.com/file/d/1SZat1W_1oBg9UTp0PuBUgCNvl9DoO8y_/view?usp=sharing){.external target="_blank"}
-   [Battleborn Battery Manual](https://drive.google.com/file/d/1h_uxY7QKgfO5nKEv_VTnyH3nFssTevif/view?usp=sharing){.external target="_blank"}
-   [Battery Chargers for Battleborn Batteries](https://drive.google.com/file/d/1kCCLJAyyoibD9HCQBgcDTTOPKOlw6Jy5/view?usp=sharing){.external target="_blank"}

## Emergency Equipment
-   [Watermaker Katadyn Survivor 6](https://drive.google.com/file/d/1z7_Gv_MGIHLaz-fmTEU4sRAAIjIN_Hmz/view?usp=sharing){.external target="_blank"}
-   [PLB-400 and 425](https://drive.google.com/file/d/1iApZFBQKeo5tq0D_GgzRP5WVA5w_AkF_/view?usp=drive_link){.external target="_blank"}
-   [ACR GlobalFIX v4](https://drive.google.com/file/d/1Y1-U1rgoReI_OhOt5oeXg-xQb_1gU99n/view?usp=drive_link){.external target="_blank"}

## Electronics: Sat Phones & Inreaches
-   [Iridium Satphone 9555](https://drive.google.com/file/d/1JeaUDUtjqRKhQYZrpApGnMIUrv-XI8J2/view?usp=drive_link){.external target="_blank"}
-   [InReach Explorer+](https://drive.google.com/file/d/1MpiZXr5R-2w96nHJxKLL8cjSBhIVd2t9/view?usp=drive_link){.external target="_blank"}
-   [InReach Explorer](https://drive.google.com/file/d/1z1TFB4qx_PZ17qTMvUI4AtCDjrWJA9az/view?usp=drive_link){.external target="_blank"}

## Electronics: Radios
-   [Handheld Radio IC-M25](https://drive.google.com/file/d/1sMeTEaX4L4db2lFjsidZn7kRSnUwWCO0/view?usp=drive_link){.external target="_blank"}
-   [Handheld Radio IC-M24](https://drive.google.com/file/d/1dugZf5yYoFsiFGEsQqfOAhv8fiMISPJj/view?usp=drive_link){.external target="_blank"}

## Electronics: Pit Tag Readers
-   [Biomark Pocket Reader](https://drive.google.com/file/d/1Wl_Ch208U8GURZwKzRWeQNL-rxN622sQ/view?usp=drive_link){.external target="_blank"}
-   [Biomark HPR Lite](https://drive.google.com/file/d/1kfk1DDM3bLhkCxFD6kehcJ6K5-CT_r_e/view?usp=drive_link){.external target="_blank"}
-   [Biomark GPR Plus](https://drive.google.com/file/d/1i6C8vzjpc7IhOkrqz7jqYbthHU1wl2jD/view?usp=drive_link){.external target="_blank"}
-   [Biomark 601 Reader](https://drive.google.com/file/d/1FhDMEIqoM74Qy9qqW1gNOQVuhIEc7hs5/view?usp=drive_link){.external target="_blank"}

## Electronics: GZ
-   [GoalZero Yeti400](https://drive.google.com/file/d/1DmRPfbMyyoBrdbTuhVNeNk4gf7Zt0dS-/view?usp=drive_link){.external target="_blank"}
-   [GoalZero Yeti150](https://drive.google.com/file/d/1AInvxz4pAlsCtti_VCfACgaSYrgqCutr/view?usp=drive_link){.external target="_blank"}
-   [GoalZero Switch10 Multi](https://drive.google.com/file/d/1h6-PYcC1HP3ITgpWfHP8RthjUmVNiv-t/view?usp=drive_link){.external target="_blank"}
-   [GoalZero Nomad100](https://drive.google.com/file/d/1UbcFJbY6QS_8vSHZ3Yf0u25o-Hm8-buB/view?usp=drive_link){.external target="_blank"}
-   [GoalZero Nomad20](https://drive.google.com/file/d/1ABauKWVa24LesHgmml31zZITR1KuCDFh/view?usp=drive_link){.external target="_blank"}
-   [GoalZero Nomad7](https://drive.google.com/file/d/1kCc8uCTcmc7Te1zXFH7FI3lrnc_UfRMC/view?usp=drive_link){.external target="_blank"}
-   [GoalZero Lantern](https://drive.google.com/file/d/1JOVah9hhOGkHH0z3BfGYaed-sRvXzuwA/view?usp=drive_link){.external target="_blank"}
-   [GoalZero Boulder100](https://drive.google.com/file/d/1eVwr8qGhe9lSkf5D9333NDnu-TSsSEms/view?usp=drive_link){.external target="_blank"}
-   [GoalZero Boulder50](https://drive.google.com/file/d/1UE8qWkElpj1OZ6gjyRibCFl6JbgdDyOl/view?usp=drive_link){.external target="_blank"}
-   [GoalZero Boulder30](https://drive.google.com/file/d/1ZBXlxz3Sat5wJ15DkpVtwNDCsnBY6EI-/view?usp=drive_link){.external target="_blank"}
-   [GoalZero Nomad28](https://drive.google.com/file/d/1luc-S3U8ZLhGlyDl9KphlGk-v-vBRR5J/view?usp=drive_link){.external target="_blank"}

## Electronics: GPS
-   [Garmin GPS76](https://drive.google.com/file/d/1QlnqZXUOd_ZXDI6JjI2Jruh2aVDY7eeE/view?usp=drive_link){.external target="_blank"}

## Electronics: Cameras and GoPros
-   [Panasonic Lumix DMC-TS6](https://drive.google.com/file/d/17ZcEi4Fg7SJWfLiTN7RJUgCItOeM3Udr/view?usp=drive_link){.external target="_blank"}
-   [Panasonic Lumix DMC-TZ3](https://drive.google.com/file/d/1rqcOQnR5ZNk9372t-nAljul7AyA0FhqK/view?usp=drive_link){.external target="_blank"}
-   [Panasonic Lumix DMC-FZ200/60](https://drive.google.com/file/d/1_SzvIedPdTg1-3as_mQfMnxcos-aoFMa/view?usp=drive_link){.external target="_blank"}
-   [Panasonic Lumix DMC-FZ70](https://drive.google.com/file/d/19KqKP3l-2WAWVU6C01vkJVaeCzNZY_pL/view?usp=drive_link){.external target="_blank"}
-   [Panasonic Lumix DMC-FZ47](https://drive.google.com/file/d/1_m_4BhSFX8tBSY53x7RdYIoaTj6FQebY/view?usp=drive_link){.external target="_blank"}
-   [Panasonic Lumix DMC-FZ35](https://drive.google.com/file/d/16DTX5j63ejvmdJQaKR69XTPfrR0zDSoP/view?usp=drive_link){.external target="_blank"}
-   [Panasonic Lumix DMC-FZ80](https://drive.google.com/file/d/16UTtOcUGq7zf9n9LqurCHrDehOuqQMSn/view?usp=drive_link){.external target="_blank"}
-   [GoPro Hero 2](https://drive.google.com/file/d/1TW1azO1H3xsso3wh5aHskWQh48AnG-tt/view?usp=drive_link){.external target="_blank"}
