---
title: "Material Safety Data Sheets"
format: html
---

[MSDS Google Drive Folder](https://drive.google.com/drive/folders/139mXtslPxeWJctK-PPYp6cxyyL1SnRtY?usp=drive_link){.external target="_blank"}


## H&Dz: LN, DMSO, Formalin, Alcohol, etc.
-   [Liquid Nitrogen](https://drive.google.com/file/d/10YuFsaWrYWCBzDVDbI8U9pWRnJ6W9VdR/view?usp=drive_link){.external target="_blank"}
-   [Isopropyl Alcohol 91%](https://drive.google.com/file/d/1jYOA6sTcCWw8wP0vUCE659AGqgKm6zP9/view?usp=drive_link){.external target="_blank"}
-   [Formalin 10%](https://drive.google.com/file/d/1IfOkI14I5YE7kk9YqK3dX9GfuTqpt3us/view?usp=drive_link){.external target="_blank"}
-   [DMSO](https://drive.google.com/file/d/1E8HdWWaN0GwlQ-xlG_0CdUPkKyeN1Vaf/view?usp=drive_link){.external target="_blank"}
-   [Betadine](https://drive.google.com/file/d/1rDy6GLWLPBrz1k6vKLBrtl3AAviJ4cLX/view?usp=drive_link){.external target="_blank"}
-   [Accel](https://drive.google.com/file/d/1FpY9T1_Pq5YtroetMLgJCQjpYW9d2A-b/view?usp=drive_link){.external target="_blank"}

## Explosives: Flares & Ammo
-   [Parachute Flare](https://drive.google.com/file/d/1V6j9mlo9Ea4V4vc_O39hBiqYi4g1c1GM/view?usp=drive_link){.external target="_blank"}
-   [Handheld Red Flare](https://drive.google.com/file/d/10nKuVCz3b0BwkQMlW5eSzDuSW31vBMeL/view?usp=drive_link){.external target="_blank"}
-   [Handheld Orange SMoke Signal](https://drive.google.com/file/d/1YZShtAZ56-jwUliZex2XeCjec13wMJ19/view?usp=drive_link){.external target="_blank"}
-   [Flare Launcher](https://drive.google.com/file/d/1J7BDWRTKLXt99s7ErWo7G2X3c6jf5Plw/view?usp=drive_link){.external target="_blank"}
-   [Ammo](https://drive.google.com/file/d/1-UmKpG5zHm0pfR0ADXxB0unoVjdELwul/view?usp=drive_link){.external target="_blank"}

## Corrosives: Bleach, Rescue, Hair Bleach
-   [Bleach](https://drive.google.com/file/d/1BXhTaDrodY3r8WA90mxpiHHhcH6gBOOe/view?usp=drive_link){.external target="_blank"}
-   [Rescue](https://drive.google.com/file/d/1LS_iKXULt_JlnadepbJguQUYh8o4_hdO/view?usp=drive_link){.external target="_blank"}
-   [Wella Color Charm Cream Developer 20 Vol 11](https://drive.google.com/file/d/136jnvoWSaKTj0nueT-Jb80F6fo0GKyER/view?usp=drive_link){.external target="_blank"}
-   [AGEbeautiful Ultra Bond Powder Lightener 2](https://drive.google.com/file/d/19g1u68I-lfCqG_MIyNig1y7YRvDF1_WU/view?usp=drive_link){.external target="_blank"}

## Flammables: Propane & Gas
-   [Propane](https://drive.google.com/file/d/1_EkXM3Gg_kl8cqZqzu9klAU99b9n55Ev/view?usp=drive_link){.external target="_blank"}
-   [Gasoline](https://drive.google.com/file/d/1b60OUiIyArObEm-aXl52vCfOM60cl_qn/view?usp=drive_link){.external target="_blank"}

## Flammables: Insecticide
-   [Raid Fogger](https://drive.google.com/file/d/1EU6SluquNr5PZy2tRp3hLbzGAcNUkG1Q/view?usp=drive_link){.external target="_blank"}
-   [Raid Ant and Roach Killer](https://drive.google.com/file/d/1LD9NWpM2wjE1aXJyeBKzVbZoneyakHdL/view?usp=drive_link){.external target="_blank"}
-   [Permethrin: Sawyer Insect Repellent](https://drive.google.com/file/d/1ahEAQwtqEy8vNSk7jg02XJMCYJcX85Hs/view?usp=drive_link){.external target="_blank"}
-   [Maxforce Complete Insecticide](https://drive.google.com/file/d/11SU70Mk2YLvpC9Ij30Di2oIP2uNt4aa7/view?usp=drive_link){.external target="_blank"}
-   [Bens 30 Wilderness Formula DEET](https://drive.google.com/file/d/14K-NrQwD6HD6ftnH3fFkjfBq8oxwlnA4/view?usp=drive_link){.external target="_blank"}
-   [Ant Traps](https://drive.google.com/file/d/1IW8SaI1keMFnfvIfLpuMPs9gKt5iS2iV/view?usp=drive_link){.external target="_blank"}

## Flammables: General Camp
-   [Purell Hand Sanitizer](https://drive.google.com/file/d/1yqcITj7zmORa-fy254QSwnE6wci3ognN/view?usp=drive_link){.external target="_blank"}

## Flammables: Camp & Boat Maintenance
-   [Wing Goop](https://drive.google.com/file/d/1Z0havxYaNeiNBF8_l3LO97OZMsJXg15I/view?usp=drive_link){.external target="_blank"}
-   [WD40](https://drive.google.com/file/d/18WX3A7ZBHMPvZKnhi4lHyxL7yJIo3MuM/view?usp=drive_link){.external target="_blank"}
-   [Vinyl Cement](https://drive.google.com/file/d/1oUX4X_flnwh1VHCPxi0VqJkLzEM5gh_M/view?usp=drive_link){.external target="_blank"}
-   [Silicone Lubricant](https://drive.google.com/file/d/1vbRpu8EY-e_cjlGELZttoz6sdcCmiXtb/view?usp=drive_link){.external target="_blank"}
-   [Silicone Grease](https://drive.google.com/file/d/1DCLMn5qlA17sjkd2nyAcCJDS3OuCXViQ/view?usp=drive_link){.external target="_blank"}
-   [PB Blaster](https://drive.google.com/file/d/1QRDujY0XJSRGbTyBkpxeNUOUAzV8GlxC/view?usp=drive_link){.external target="_blank"}
-   [Motor Oil 10W-30](https://drive.google.com/file/d/1aPKJ8MNinUdQFWlK_AgnvAitUdx3QQpG/view?usp=drive_link){.external target="_blank"}
-   [Marine Carb and Choke Cleaner](https://drive.google.com/file/d/1S51A_ORVtIMTGabNZ0O3lULRx4wei0qt/view?usp=drive_link){.external target="_blank"}
-   [Marine Tex](https://drive.google.com/file/d/1mRHD3058-eQMeEPgSyEOR4yvZh2ptAIe/view?usp=drive_link){.external target="_blank"}
-   [LPS Silicone Lubricant](https://drive.google.com/file/d/1_BJ5fmWPwMXHZsAJ_52Hwi3QBP9z-G3J/view?usp=drive_link){.external target="_blank"}
-   [Lower Unit Oil 80W-90](https://drive.google.com/file/d/1QqmEEfvVxJ_n6R-RVGCR1_lwVHPPtGMc/view?usp=sharing){.external target="_blank"}
-   [Krazy Glue](https://drive.google.com/file/d/1vftCQI2otmqqAFTwec_ehpg3alnjb8zJ/view?usp=drive_link){.external target="_blank"}
-   [Fuel Stabilizer](https://drive.google.com/file/d/1_3Qne1d5cEX_lbnGMN2dyhwdP9JZY4_k/view?usp=drive_link){.external target="_blank"}
-   [Epoxy 5 and 10 Minute](https://drive.google.com/file/d/1yMpE4TWyzPb-4u--hya0l1uHcQZgqoAF/view?usp=drive_link){.external target="_blank"}
-   [Dielectric Grease](https://drive.google.com/file/d/1cgx9O_zPvI6BxBq7Gk9oJwBlgHdrTnTH/view?usp=drive_link){.external target="_blank"}
-   [Corrosion Block](https://drive.google.com/file/d/1zAvY2RiqoKsIpyxvJimsVitHmXpYlA-I/view?usp=drive_link){.external target="_blank"}
-   [Carb and Choke Cleaner](https://drive.google.com/file/d/1xzKDnzPE4BUPNifeff4qqoy_qt0gjzGT/view?usp=drive_link){.external target="_blank"}
-   [Boat Oil 10W-30](https://drive.google.com/file/d/10Uk-VTchccdcK4EvJxcTMhjv5Cl9SdLT/view?usp=drive_link){.external target="_blank"}
-   [Barge Cement](https://drive.google.com/file/d/1GXPU9XFs5GEsjSqTdPXy9AtNlpCENLYJ/view?usp=drive_link){.external target="_blank"}
-   [5200 Marine Sealant](https://drive.google.com/file/d/1k1DsENKT3BHGNWwBrDc6OCzEL9I4NO2a/view?usp=drive_link){.external target="_blank"}
-   [12v Battery](https://drive.google.com/file/d/1vptBTRAYwoyCLZCDqzgvYqXQ498DvFe6/view?usp=drive_link){.external target="_blank"}
-   [5 Minute Epoxy](https://drive.google.com/file/d/1u7PSfmjJx6EwP8d8B7j0-47oI0Z7zTFx/view?usp=drive_link){.external target="_blank"}
