---
title: Onboarding Paperwork
---

Contains information and required paperwork for new hires.

## NOAA
-   [2025 Administrative/Orientation Information](https://docs.google.com/document/d/13uRDwDVw_rAtg3rR4IGUthAlL20VHHP2O9BSOheNgFM/edit){.external target="_blank"}
-   [Hiring Checklist](https://docs.google.com/spreadsheets/d/1c0ytT9lpYq_nSaTrdw0FW_U7tRS94vj_sfW4xp6hkcU/edit?gid=0#gid=0){.external target="_blank"}
-   [NOAA Sexual Assault and Sexual Harrassment Prevention](https://drive.google.com/file/d/14V4sWz1LjCsKqd7HdQhlXUJh6BNBLvM1/view?usp=sharing){.external target="_blank"}
-   [PIFSC Values Document](https://drive.google.com/file/d/1yR0ftG3OXy9g64ZuuwZNus9DNlvuIGbw/view?usp=sharing){.external target="_blank"}

## RCUH/CIMAR
Consolidated attachments from RCUH new hire email

-   [RCUH New Hire Reference Guide for Regular Hires](https://drive.google.com/file/d/1JU45wljUc92xpV-t2qZ0Dw9IXJLKQNlZ/view?usp=drive_link){.external target="_blank"}
-   [New Hire Project Orientation Checklist](https://drive.google.com/file/d/18UA8JDiipA4RfK7S3uliWz9jgk1hQvlV/view?usp=drive_link){.external target="_blank"}
-   [Instructions- UH Email & ID Number](https://drive.google.com/file/d/133VMhmIdR0Aeee_w9jpHCs129TcI-PD5/view?usp=drive_link){.external target="_blank"}
-   [Hawaii State Ethics Information](https://drive.google.com/file/d/1lJLj5P3KOR5hMYuIefzGm0Aa2_nwvdVn/view?usp=drive_link){.external target="_blank"}
-   [eTimesheet User Guide](https://drive.google.com/file/d/1xQ3wIcOJviVOTkw7u19dNeKr8TFkcGCy/view?usp=drive_link){.external target="_blank"}
-   [Instructions for form I-9](https://drive.google.com/file/d/1KI4fc72XUNMORbwi7HM9q20sfodCgDM0/view?usp=drive_link){.external target="_blank"}
-   [NBS FSA Overview](https://drive.google.com/file/d/1O5KleD8cwnmbQUotU0qaDqaYSg9_1ItH/view?usp=drive_link){.external target="_blank"}
-   [TIAA Retirement Information](https://drive.google.com/file/d/1aMcocytOBGUr7hKLMaFe8JBxnfKivm_x/view?usp=drive_link){.external target="_blank"}
-   [CIMAR Employee Timesheet Payday Schedule 2025](https://drive.google.com/file/d/1kiLq003bWQJDx6IvEcI16LVAywJfES9y/view?usp=drive_link){.external target="_blank"}
-   [RCUH Human Resources & Employee Self-Service](https://hr.rcuh.com/psp/hcmprd/EMPLOYEE/EMPL/?cmd=login&languageCd=ENG&){.external target="_blank"}

##  Reimbursement Forms
-   [2025 Clothing Reimbursements](https://docs.google.com/document/d/1fos5_3MXhcizLh_U3jbKL6mF6iAuyjmnY-kYWtFTfqA/edit?usp=sharing){.external target="_blank"}
-   [CIMAR Cash Reimbursements](https://docs.google.com/document/d/1HfbjMestBEK0zHwdIjJnwF3GDy0Xf8uv2W8xPkab9To/edit?usp=sharing){.external target="_blank"}

##  Ships
See [ship paperwork](https://pifsc-protected-species-division.github.io/PMNM-ARCamps-Manual/content/ShipPaperwork.html).

## Points of Contact

-   lizabeth.kashinsky@noaa.gov 
-   cimarhr@soest.hawaii.edu
-   rcuh_employment@rcuh.com

